### ISSUE TITLE
Status not readable without web font

### ISSUE THREAD

**Issue by alexgibson** [mozmeao/status.mozmar.org#2]
I block web fonts on my phone, so the status isn't easily readable. It would be nice if it degraded gracefully, or even better we could switch to using SVG icons?

![status](https://cloud.githubusercontent.com/assets/400117/17094403/ef913640-5246-11e6-833d-23364395f17e.png)

Bonus points for fixing scaling on the heading, and also making it an `h1` 😄

**Comment by glogiotatidis** [comment]
Good points all @alexgibson. This is the best I could do in the frontend, happy to merge PRs fixing what you list :)

**Comment by alexgibson** [comment]
Sure, I'd be happy to help out here :)
