### ISSUE TITLE
Status.yml update interval

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/status.mozmar.org#23]
Opening up a dev console on status.mozmar.org shows a requrest for `status.yml` every couple of seconds but in code we've set it up to [60 secs](https://github.com/mozmar/status.mozmar.org/blob/6132f983b8552ec8d894b9083c1957adc41390fb/local-dev/src/components/StatusBoard.js#L241)

Any ideas what's going on @jpetto ?

**Comment by jpetto** [comment]
Hm, in the `/docs` directory, the [built JS file has an interval of 3 seconds](https://github.com/mozmar/status.mozmar.org/blob/master/docs/main.a2626f52aa16b6f6c7e5.js) (search for "interval"). The source file sure enough has the interval set to 60 seconds. The built JS file shows to be updated in the same commit as the source file. So this is...odd.

I definitely have set the interval to a shorter time when testing locally. Perhaps the local build happened prior to setting the interval back to 60 seconds? (Though I think this would assume you also set the interval to a lower number locally...)

We should just need to re-build the React app and submit a PR. Will do so shortly.

**Comment by jpetto** [comment]
Opened #25.

Are we opening PR's against the `master` or `develop` branch? What's the difference?

**Comment by glogiotatidis** [comment]
> I definitely have set the interval to a shorter time when testing locally. Perhaps the local build happened prior to setting the interval back to 60 seconds? (Though I think this would assume you also set the interval to a lower number locally...)

I do the same thing so maybe I mixed my build steps. Two things to prevent this from happening in the future:
1. Is there a way to have local settings to set things like interval value without changing the code?
2. Would it be useful to make Travis auto-build and deploy to `/docs` when we push code to `local-dev`?

**Comment by glogiotatidis** [comment]
> Are we opening PR's against the master or develop branch? What's the difference?

We pull request against `develop` which is the default. Commits to default get automatically pushed to https://github.com/mozmar/status.ramzom.org and we can test code in the staging site http://status.ramzom.org.

Then we manually merge to master to update production site.

**Comment by jpetto** [comment]
> I definitely have set the interval to a shorter time when testing locally. Perhaps the local build happened prior to setting the interval back to 60 seconds? (Though I think this would assume you also set the interval to a lower number locally...)
> 
> I do the same thing so maybe I mixed my build steps. Two things to prevent this from happening in the future:
> 1. Is there a way to have local settings to set things like interval value without changing the code?

Hmm, good question. I will look in to this.

> 1. Would it be useful to make Travis auto-build and deploy to /docs when we push code to local-dev?

I was thinking the same thing. If it's not tricky to set up/maintain, then I'm all for it.

**Comment by glogiotatidis** [comment]
> 1. Is there a way to have local settings to set things like interval value without changing the code?
> 
> Hmm, good question. I will look in to this.

Filed #26 

> ```
>     Would it be useful to make Travis auto-build and deploy to /docs when we push code to local-dev?
> ```
> 
> I was thinking the same thing. If it's not tricky to set up/maintain, then I'm all for it.

Filed #27

**Comment by glogiotatidis** [comment]
I'm closing this one since we fixed the issue and we decided on steps forward 👍
