### ISSUE TITLE
TLS observatory integration

### ISSUE THREAD

**Issue by jgmize** [mozmeao/status.mozmar.org#31]
1. Use https://github.com/mozilla/observatory-cli poll our websites and populate yaml file(s) in the master branch of this repo
2. Display alert if cert will expire soon (and for other issues in a possible future iteration)
3. Link to full report on observatory on observatory.mozilla.org, for example: https://observatory.mozilla.org/analyze.html?host=www.mozilla.org

**Comment by jgmize** [comment]
Alternative to using the observatory-cli for step 1: use the openssl cli (example bash functions: https://github.com/jgmize/dotfiles/blob/master/.bash_functions.d/certs) to get the expiration date and a little bit of date parsing logic to determine if the cert is about to expire and update the appropriate yaml file with the status.

**Comment by glogiotatidis** [comment]
Moved to mozmar/status
