### ISSUE TITLE
service detail page outline/structure

### ISSUE THREAD

**Issue by jpetto** [mozmeao/status.mozmar.org#4]
Let's paint the bikeshed that is the upcoming service detail page. This will also help us plan the YAML alert(s) file structure.

`status.mozmar.org/service/:serviceslug`
# Service Name (w/ group name & current status icon)
## General notes

[link to add another note]() (points to GitHub editor)
### Title

Date/Time
Severity
Description
Resolved?
External link
Graph (iframed)
Notes
[link to add another note]() (points to GitHub editor)

**Comment by jpetto** [comment]
Do we want/need both general service level notes _and_ alert level notes?

@jgmize @glogiotatidis - Thoughts on the proposed structure?

**Comment by jgmize** [comment]
> Do we want/need both general service level notes and alert level notes?

An example use case for a "general service level note" would be where we become aware of a degraded service level that is below the threshold of an automated alert, but that functionality could be potentially be achieved by creating a "manual alert" for the service with a note, so I think just having "alert level notes" is probably sufficient.

**Comment by glogiotatidis** [comment]
Moved to mozmar/status
