### ISSUE TITLE
Add build step to gh-pages branch

### ISSUE THREAD

**Issue by jpetto** [mozmeao/status.mozmar.org#7]
To make it easier to re-use components, leverage npm modules, and get on the single page app bandwagon, I put together a version of the `gh-pages` branch based off the new [Create React App](https://github.com/facebookincubator/create-react-app) boilerplate.

Repo - [github.com/jpetto/test.status.mozmar.org](https://github.com/jpetto/test.status.mozmar.org)
Live `gh-pages` branch - [mozmar.equalparts.io/](http://mozmar.equalparts.io/)

The `local-dev` folder is where all, uh, local development happens. In that folder (after running `npm install`), you can run `npm run start` and get a live-reloading local server. Running `npm run build` creates a compressed/hashed/babel-ified build in a `build` directory. You can `cd` into `build` and run `python -m SimpleHTTPServer` to test the build. After confirming the build is successful, you can run `npm run finalize` which will move all the files out of `build` and into the root directory (which is what will be served via GitHub's magic). You then do the normal `git add`/`git commit`/`git push` to put the changes up on the interwebs.

Not nearly as simple & straight forward as what we have now, but it'll give us more flexibility going forward.

Give it a fork/local try and let me know what you think.

**Comment by jpetto** [comment]
@glogiotatidis @jgmize @alexgibson - Can y'all give this a run and let me know what you think? Too convoluted? Too messy having dev and prod code in the same branch?

**Comment by alexgibson** [comment]
Looks ok to me, although I haven't dived that deep in how things are set up currently.

Could an alternative option be to have all code in the `master` branch, with `/src` and `/dist` directories? You could than add a gulp task to build the static page, run some tests (?), then take the `/dist` contents and commit them to the `gh-pages` branch? I did this not long ago [here as an example](https://github.com/alexgibson/wavepad), although this may not be quite a simple. It does keep things nice and clean though (as you can add `/dist` to `.gitignore`).

**Comment by alexgibson** [comment]
I also just came across this out of chance: https://github.com/mozilla/neo

**Comment by jpetto** [comment]
I did initially try a version using [`gh-pages`](https://www.npmjs.com/package/gh-pages), but it fell short in that it couldn't _not_ push to the remote repo. Setting `push: false` resulted in no commit at all. The approach is very attractive, but I'm not really on board with an automated push to prod in this instance. Maybe I'll file a PR to fix the npm package. 😁 

Noting that Mozilla React boilerplate repo for future use. 👍

**Comment by alexgibson** [comment]
I totally understand the hesitation for larger sites, but for something like this i think it would be ok, as long as we had a testing step that verifies things between the build / push step. I understand that's more work though, and probably out of scope for this change 👍
